name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-check:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      # ---- Backend (/backend) ----
      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Lint backend (non-blocking)
        working-directory: backend
        run: npm run lint --if-present
        continue-on-error: true

      - name: Test backend (unit only)
        working-directory: backend
        run: npm test --if-present

      # ---- Frontend (/frontend) ----
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Lint frontend (non-blocking)
        working-directory: frontend
        run: npm run lint --if-present
        continue-on-error: true

      - name: Build frontend
        working-directory: frontend
        run: npm run build
